# Homework4

## 【題目】

用物件導向的方式，建立屬於自己的normal scaler（標準化），其中要包含fit及transform功能

### 1.載入sklearn的StandardScaler

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([ 0.5,  0.5])

In [6]:
scaler.scale_

array([ 0.5,  0.5])

In [7]:
scaler.var_

array([ 0.25,  0.25])

In [8]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [9]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

### 2.寫出自己的StandardScaler，命名為myStandardScaler，並fit、transform和fit_transform

In [10]:
import numpy as np

In [11]:
class myStandardScaler:
    def __init__(self):
        self.mean_ = None
        self.scale_ = None
        
    def fit(self, data):
        self.mean_ = np.mean(data, axis = 0)
        self.scale_ = np.std(data, axis = 0)
        
    def transform(self, data):
        new_data = (np.array(data) - self.mean_)/self.scale_
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [12]:
myscaler = myStandardScaler()

In [13]:
myscaler.fit(data)

In [14]:
myscaler.mean_

array([ 0.5,  0.5])

In [15]:
myscaler.scale_

array([ 0.5,  0.5])

In [16]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [17]:
myscaler_new = myStandardScaler()

In [18]:
myscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])